name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Cache go modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build 
      run: go get github.com/swaggo/swag/cmd/swag && make build

    - name: Pack
      run: |
        rm cloudiac_v*.tar.gz cloudiac-repos_v*.tar.gz cloudiac-providers_v*.tar.gz && \
        make package && make repos-package && make providers-package && \
        mv cloudiac_v*.tar.gz cloudiac_$VERSION.tar.gz && \
        mv cloudiac-repos_v*.tar.gz cloudiac-repos_$VERSION.tar.gz && \
        mv cloudiac-providers_v*.tar.gz cloudiac-providers_$VERSION.tar.gz

    - name: Show versions
      run: ./build/iac-portal --version && ./build/ct-runner --version

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      files: |
        cloudiac_$VERSION.tar.gz
        cloudiac-repos_$VERSION.tar.gz
        cloudiac-providers_$VERSION.tar.gz

